name: pokemon
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  navigation:
    path: ./navigation
  feature:
    path: ./feature

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz:
  shared_preferences:
  internet_connection_checker:
  flutter_bloc:
  get_it:
  json_annotation:
  build_runner:
  json_serializable:
  cached_network_image:
  flutter_svg:
  http: ^0.13.6
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons:
  flutter_localizations:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - core_ui/lib/src/assets/images/noImage.png
    - core_ui/lib/src/assets/images/pokeball.png
    - core_ui/lib/src/assets/images/straighten.svg
    - core_ui/lib/src/assets/images/weight.svg
    - core/resources/en.json
    

fonts:
    - family: Poppins
      fonts:
        - asset: core_ui/lib/src/fonts/Poppins-Regular.ttf
        - asset: core_ui/lib/src/fonts/Poppins-Bold.ttf
          weight: 700
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "core_ui/lib/src/assets/images/icon.png"